name: Release
description: Automate the release process using semantic-release

inputs:
  github-token:
    description: The GitHub token to use for authentication
    required: true

runs:
  using: "composite"
  steps:
    - id: checkout
      name: Checkout
      uses: actions/checkout@v4

    - id: setup-node
      name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "lts/*"

    - id: install-dependencies
      name: Install dependencies
      shell: bash
      run: |
        npm install \
          semantic-release \
          @semantic-release/commit-analyzer \
          @semantic-release/release-notes-generator \
          @semantic-release/changelog \
          @semantic-release/git \
          @semantic-release/github \
          @semantic-release/exec

    - id: release
      name: Release
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: bash
      run: |
        npx semantic-release
