name: Build and Push Container
description: Build and push a container image to Artifact Registry

inputs:
  workload_identity_provider:
    description: The workload identity provider to use for authentication
    required: true
  service_account:
    description: The service account to use for authentication
    required: true
  artifact_registry_region:
    description: The region of the Artifact Registry
    required: true
  artifact_registry_name:
    description: The name of the Artifact Registry
    required: true
  artifact_registry_application:
    description: The name of the application in the Artifact Registry
    required: true
  gcp_project_name:
    description: The GCP project to use
    required: true
  version:
    description: The version of the container image
    required: true

runs:
  using: "composite"
  steps:

    - id: checkout
      name: Checkout
      uses: actions/checkout@v4

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - uses: google-github-actions/setup-gcloud@v2
      with:
        version: latest

    - name: sign-in to artifact registry
      run: |
        gcloud auth configure-docker ${{ inputs.artifact_registry_region }} --quiet

    - name: Build and Push Container
      run: |-
        docker build -t "${{ inputs.artifact_registry_region }}/${{ inputs.gcp_project_name }}/${{ inputs.artifact_registry_name }}/${{ inputs.artifact_registry_application }}:${{ inputs.version }}" ./
        docker push "${{ inputs.artifact_registry_region }}/${{ inputs.gcp_project_name }}/${{ inputs.artifact_registry_name }}/${{ inputs.artifact_registry_application }}:${{ inputs.version }}"
